[package]
name = "{{project-name}}-installer"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Path resolution + setup/uninstall"

[dependencies]
{{project-name}}-config = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = "3"
